name: Build and publish docker image 

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: checkout main branch for github
        run: mvn -B package --file pom.xml

      - name: Run tests with Maven
        run: mvn -B test --file pom.xml



